@url = http://localhost:3000
@identity_provider=http://localhost:8080


###
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
  "name": "Campaing 3",
  "content": "Description of Campaign 4",
  "emails": ["test@email.com", "test1@email.com", "test2@email.com"]
}

###
GET {{url}}/campaigns
Authorization: Bearer {{access_token}}

###
GET {{url}}/campaigns/cq2ufkejp3qus68taoig
Authorization: Bearer {{access_token}}

###
PATCH {{url}}/campaigns/cancel/cq285tejp3qksp0r7uj0
Authorization: Bearer {{access_token}}

###
DELETE {{url}}/campaigns/delete/cq285tejp3qksp0r7uj0
Authorization: Bearer {{access_token}}

###
# @name token
POST {{identity_provider}}/realms/emailn_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=thiago.adsix@gmail.com&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}